name: Border0 RDP Access

on:
  push:
  workflow_dispatch:

jobs:
  expose-rdp:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Enable Remote Desktop and Set Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
       
    # - name: Download cloudflare CLI 
    #   run: |
    #     Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
    
    # # - name: Install CLI
    # #   run: Start-Process msiexec.exe -Wait -ArgumentList '/i installer.msi /quiet'


    # # - name: Authenticate with Border0
    # #   run: .\border0.exe login --service-token $Env:BORDER0_TOKEN
    # #   env:
    # #     BORDER0_TOKEN: ${{ secrets.BORDER0_TOKEN }}

    # - name: Create Cloudflare Tunnel to RDP
    #   run: Start-Process -NoNewWindow -FilePath ".\cloudflared.exe" -ArgumentList "tunnel", "--no-autoupdate", "--url", "tcp://localhost:3389"


    #   # run: .\border0.exe socket create --name github-rdp --backend-type tcp --backend-host 127.0.0.1 --backend-port 3389


    - name: Download and Extract LocalXpose Binary
      run: |
        Invoke-WebRequest -Uri "https://loclx-client.s3.amazonaws.com/loclx-windows-amd64.zip" -OutFile "loclx.zip"
        Expand-Archive loclx.zip -DestinationPath .

    - name: Install wexpect and Login to LocalXpose using Python script
      env:
        LOCXPOSE_TOKEN: ${{ secrets.LOCXPOSE_TOKEN }}
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install wexpect
        python -c "
        import wexpect
        child = wexpect.spawn('loclx.exe account login')
        child.expect('please type your access token')
        child.sendline('${Env:LOCXPOSE_TOKEN}')
        child.expect(wexpect.EOF)
        print(child.before)
        "

    - name: Start LocalXpose TCP Tunnel and Keep Alive
      run: |
        Start-Process -NoNewWindow -FilePath ".\loclx.exe" -ArgumentList "tunnel tcp --port 3389 --to 127.0.0.1:3389"
        for ($i = 0; $true; $i++) {
          Write-Host "[$i] Tunnel running... $(Get-Date -Format 'HH:mm:ss')"
          Start-Sleep -Seconds 30
        }
