name: Border0 RDP Access

on:
  push:
  workflow_dispatch:

jobs:
  expose-rdp:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Enable Remote Desktop and Set Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
       
    - name: Download Border0 CLI Installer
      run: |
        Invoke-WebRequest -Uri "https://download.border0.com/desktop/windows_amd64/border0-installer.exe" -OutFile border0-installer.exe
    
    - name: Install Border0 CLI
      run: Start-Process -FilePath ".\border0-installer.exe" -ArgumentList "/S" -Wait


    - name: Authenticate with Border0
      run: .\border0.exe login --service-token $Env:BORDER0_TOKEN
      env:
        BORDER0_TOKEN: ${{ secrets.BORDER0_TOKEN }}

    - name: Create and Connect Socket to Expose RDP (Port 3389)
      run: .\border0.exe socket create --name github-rdp --backend-type tcp --backend-host 127.0.0.1 --backend-port 3389
